---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php support packages and update cache
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

