---

- hosts: all
  become: true
  pre_tasks:

  - name: upgrade dist and  update cache for RedHat of family
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: (ansible_os_family == "RedHat") or (ansible_distribution == "CentOS")

  - name: upgrade dist and  update cache for Debian os family
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: (ansible_os_family == "Debian") and (ansible_distribution == "Ubuntu")

  - name: upgrade dist and  update cache for Debian os family
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: (ansible_os_family == "Debian") and (ansible_distribution == "Kali")



- hosts: all
  become: true
  roles:
    - base


#- hosts: workstations
#  become: true
#  roles:
#    - workstations


- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers
    

- hosts: file_servers
  become: true
  roles:
    - file_servers
