---

- hosts: all
  become: true
  pre_tasks:

  - name: upgrade dist and  update cache for RedHat of family
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: (ansible_os_family == "RedHat") or (ansible_distribution == "CentOS")

  - name: upgrade dist and  update cache for Debian os family
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: (ansible_os_family == "Debian") and (ansible_distribution == "Ubuntu")

  - name: upgrade dist and  update cache for Debian os family
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: (ansible_os_family == "Debian") and (ansible_distribution == "Kali")



- hosts: all
  become: true
  tasks:

  - name: add ssh key for cyberninja
    tags: always
    authorized_key:
      user: cyberninja
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINP6ewim5rhHjQHlmIGcquQQcK49Ne+mBxdxT4tX02st ansible"


#- hosts: workstations
#  become: true
#  tasks:
#  
#  - name: install unzip
#    package:
#      name: unzip
#
#  - name: install terraform
#    unarchive:
#      src: https://releases.hashicorp.com/terraform/1.2.8/terraform_1.2.8_linux_amd64.zip
#      dest: /usr/local/bin
#      remote_src: yes
#      owner: root
#      group: root
#      mode: 0755


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php support packages for Debian os family
    tags: apache,apache2,ubuntu,cutefish
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: (ansible_os_family == "Debian") or (ansible_distribution == "Ubuntu")

  - name: install apache2 and php support packages for RedHat os family
    tags: apache,centos,alma,fedora,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: (ansible_os_family == "RedHat") or (ansible_distribution == "CentOS")

  - name: start apache2 (Debian)
    tags: apache, httpd, apache2
    service:
      name: apache2
      state: started
      enabled: yes
    when: (ansible_distribution == "Kali") or (ansible_os_family == "Debian")

  - name: change e-mail address for admin
    tags: apache, httpd, apache2
    lineinfile: 
      path: /etc/apache2/apache2.conf
      regexp: "^# ServerAdmin"
      line: "# * This is the new root server admin's email root@localhost.com"
    when: (ansible_distribution == "Kali") or (ansible_os_family == "Debian")
    register: apache2

  - name: restart apache2 (Debian)
    tags: apache, httpd, apache2
    service:
      name: apache2
      state: restarted
    when: apache2.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
    
  - name: install mariadb package (cutefish|ubuntu)
    tags: db,mariadb,ubuntu,cutefish
    apt:
      name: mariadb-server
      state: latest
    when: ansible_os_family == "Debian"

  - name: install mariadb package (Centos|Fedora|Almalinux)
    tags: db,mariadb,centos,alma,fedora
    yum:
      name: mariadb
      state: latest
    when: ansible_os_family == "RedHat"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package for all os family
    tags: samba
    package:
      name: samba
      state: latest

