---

- hosts: all
  become: true
  pre_tasks:

  - name: upgrade dist and  update cache for RedHat of family
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: (ansible_os_family == "RedHat") or (ansible_distribution == "CentOs")

  - name: upgrade dist and  update cache for Debian os family
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: (ansible_os_family == "Debian") and (ansible_distribution == "Ubuntu")

  - name: upgrade dist for cutefish
    tags: always
    apt:
      upgrade: dist
    when: (ansible_os_family == "Debian") and (ansible_distribution == "Cutefish")

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php support packages and update cache for Debian os family
    tags: apache,apache2,ubuntu,cutefish
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: (ansible_os_family == "Debian") or (ansible_distribution == "Ubuntu")


  - name: install apache2 and php support packages and update cache for RedHat os family
    tags: apache,centos,alma,fedora,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: (ansible_os_family == "RedHat") or (ansible_distribution == "CentOs")

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
    
  - name: install mariadb package (cutefish|ubuntu)
    tags: db,mariadb,ubuntu,cutefish
    apt:
      name: mariadb-server
      state: latest
    when: ansible_os_family == "Debian"

  - name: install mariadb package (Centos|Fedora|Almalinux)
    tags: db,mariadb,centos,alma,fedora
    yum:
      name: mariadb
      state: latest
    when: ansible_os_family == "RedHat"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package for all os family
    tags: samba
    package:
      name: samba
      state: latest

